### ISSUE TITLE
A problem I meet in spatial_cnn and spatial_dataloader

### ISSUE THREAD

**Issue by ttthappy** [jeffreyhuang1/two-stream-action-recognition#22]
Dear jeffreyhuang,
I read your readme, the input of spatial_cnn is from feichtenhofer/twostreamfusion ,
So the path in spatial_cnn and spatial_dataloader equals to feichtenhofer’s Directory.
Is it right?
When I run the spatial_cnn, I have a problem:

Traceback (most recent call last):
  File "/home/tangjun/jeffreyhuang/two-stream-action-recognition/spatial_cnn.py", line 272, in <module>
    main()
  File "/home/tangjun/jeffreyhuang/two-stream-action-recognition/spatial_cnn.py", line 55, in main
    train_loader, test_loader, test_video = data_loader.run()
  File "/home/tangjun/jeffreyhuang/two-stream-action-recognition/dataloader/spatial_dataloader.py", line 100, in run
    train_loader = self.train()
  File "/home/tangjun/jeffreyhuang/two-stream-action-recognition/dataloader/spatial_dataloader.py", line 133, in train
    print(training_set[1][0]['img1'].size())
  File "/home/tangjun/jeffreyhuang/two-stream-action-recognition/dataloader/spatial_dataloader.py", line 60, in __getitem__
    data[key] = self.load_ucf_image(video_name, index)
  **File "/home/tangjun/jeffreyhuang/two-stream-action-recognition/dataloader/spatial_dataloader.py", line 30, in load_ucf_image
    img = Image.open(path +str(index)+'.jpg')**
  File "/home/tangjun/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2272, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/home/tangjun/dataset1/jpegs_256/Swing/separated_images/v_Swing_g09_c02/v_Swing_g09_c02_29.jpg'

Best regards,
Yours sincerely
 Tang Jun

**Comment by Zhuysheng** [comment]
hello @ttthappy  do you solve it, I meet the same question

**Comment by menon92** [comment]
Hello @ttthappy @Zhuysheng,
Do you solve the problem. I have the same problem

**Comment by Atul997** [comment]
@ttthappy @Zhuysheng @menon92 
Did you solve the problem, as i m getting the same error.

**Comment by menon92** [comment]
@Atul997
You need to modify your `spatial_dataloader.py` to solve this problem
