### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by fcxmcc** [jeffreyhuang1/two-stream-action-recognition#47]
i try to reload the spatial model but it's not useful,,,.....    the report errors as follows:

torch.Size([3, 224, 224])
==> Validation data :71877frames
torch.Size([3, 224, 224])
==> Build model and setup loss and optimizer
==> loading checkpoint 'record/spatial/spatial_video_preds.pickle'
Traceback (most recent call last):
  File "/home/xm/python/action/two-stream-action-recognition-master/spatial_cnn.py", line 268, in <module>
    main()
  File "/home/xm/python/action/two-stream-action-recognition-master/spatial_cnn.py", line 65, in main
    model.run()
  File "/home/xm/python/action/two-stream-action-recognition-master/spatial_cnn.py", line 109, in run
    self.resume_and_evaluate()
  File "/home/xm/python/action/two-stream-action-recognition-master/spatial_cnn.py", line 93, in resume_and_evaluate
    checkpoint = torch.load(self.resume)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)

**Comment by loweite** [comment]
add code "#coding:utf-8"  at the top of  spatial_cnn.py file

**Comment by wcyy0123** [comment]
pickle_module.load(f)
->
pickle.load(f,encoding='bytes')
