### ISSUE TITLE
no CUDA-capable device is detected (only for motion network)

### ISSUE THREAD

**Issue by duygusar** [jeffreyhuang1/two-stream-action-recognition#52]
I was able to run the spatial network, but when I try to run motion.network I get this error (which is super weird because obviously I run it on the same exact system/environment/terminal):

two-stream-action-recognition-master/venv/local/lib/python2.7/site-packages/torchvision/transforms/transforms.py:208: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
==> Training data : 573  videos (20, 224, 224)
==> Validation data : 4294  frames (20, 224, 224)
==> Build model and setup loss and optimizer
**THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=38 : no CUDA-capable device is detected**
Traceback (most recent call last):
  File "motion_cnn.py", line 264, in <module>
    main()
  File "motion_cnn.py", line 67, in main
    model.run()
  File "motion_cnn.py", line 112, in run
    self.build_model()
  **File "motion_cnn.py", line 86, in build_model
    self.model = resnet101(pretrained= True, channel=self.channel).cuda()**
  File "/media/d/DATA_2/two-stream-action-recognition-master/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/media/d/DATA_2/two-stream-action-recognition-master/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/media/d/DATA_2/two-stream-action-recognition-master/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/media/d/DATA_2/two-stream-action-recognition-master/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:74

I have only one GPU so I don't understand why this is happening, I tried to set the GPU with CUDA_VISIBLE_DEVICES=0 but it didn't work (export CUDA_VISIBLE_DEVICES=0 didn't work either)

**Comment by duygusar** [comment]
I just noticed os.environ["CUDA_VISIBLE_DEVICES"] = "1" !! My bad!
